/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./../components/AudioPlayer.vue')['default']
    CoverCard: typeof import('./../components/CoverCard.vue')['default']
    DeclarationBanner: typeof import('./../components/DeclarationBanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
